<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
// $routes->get('/', 'Home::index');
$routes->get('onboard', 'Onboard::index');
$routes->post('onboard/create', 'Onboard::create');
$routes->get('login', 'Auth::login');
$routes->get('logout', 'Auth::logout');
// $routes->post('login', 'Auth::login');
$routes->get('register', 'Auth::register');
$routes->post('register', 'Register::register');
$routes->post('register/usernameValidation', 'Register::usernameValidation');
$routes->post('register/emailValidation', 'Register::emailValidation');
$routes->post('register/registerData', 'Register::registerData');
$routes->post('login/loginValidate', 'Auth::loginValidate');
$routes->get('rest_api/session', 'Rest_api::session');
$routes->get('rest_api/dashboard-template', 'Rest_api::dashboardTemplate');
$routes->get('rest_api/dashboard-products', 'Rest_api::dashboardProducts');
$routes->get('rest_api/dashboard-categories', 'Rest_api::dashboardCategories');
$routes->get('rest_api/catalog-filters', 'Rest_api::catalogFilters');
$routes->get('rest_api/catalog-products', 'Rest_api::catalogProducts');
$routes->get('rest_api/product/(:num)', 'Rest_api::productDetails/$1');
$routes->get('rest_api/related-products', 'Rest_api::relatedProducts');
$routes->get('rest_api/product-reviews/(:num)', 'Rest_api::productReviews/$1');
$routes->post('rest_api/product-reviews/(:num)', 'Rest_api::saveProductReview/$1');
$routes->post('rest_api/coupon', 'Rest_api::validateCoupon');
$routes->get('rest_api/orders', 'Rest_api::orders');
$routes->post('rest_api/checkout', 'Rest_api::checkout');
$routes->get('rest_api/payment/config', 'Rest_api::paymentConfig');
$routes->post('rest_api/payment/create', 'Rest_api::createPaymentOrder');
$routes->post('rest_api/payment/verify', 'Rest_api::verifyPayment');
$routes->get('api/auth/session', 'Rest_api::session');
$routes->get('admin/dashboard', 'Dashboard::dashboard');
$routes->get('admin/notifications', 'Notifications::index');
$routes->get('admin/notifications/conversations', 'Notifications::conversations');
$routes->get('admin/notifications/messages/(:num)', 'Notifications::messages/$1');
$routes->get('admin/notifications/unread-count', 'Notifications::unreadCount');
$routes->post('admin/notifications/create', 'Notifications::create');
$routes->post('admin/notifications/send/(:num)', 'Notifications::send/$1');
$routes->post('admin/notifications/read/(:num)', 'Notifications::markRead/$1');
$routes->get('admin/dashboard-template', 'Dashboard::dashboardTemplateList');
$routes->get('admin/dashboard-template/create', 'Dashboard::dashboardTemplateView');
$routes->get('admin/dashboard-template/edit/(:num)', 'Dashboard::dashboardTemplateView/$1');
$routes->post('admin/dashboard-template/save', 'Dashboard::saveDashboardTemplate');
$routes->post('admin/dashboard-template/upload-image', 'Dashboard::uploadDashboardTemplateImage');
$routes->get('/', 'Dashboard::userDashboard');
$routes->get('user/dashboard', 'Dashboard::userDashboard');
$routes->get('api/user/dashboard-template', 'Rest_api::dashboardTemplate');
$routes->get('api/user/dashboard-products', 'Rest_api::dashboardProducts');
$routes->get('api/user/dashboard-categories', 'Rest_api::dashboardCategories');
$routes->get('api/user/catalog-filters', 'Rest_api::catalogFilters');
$routes->get('api/user/catalog-products', 'Rest_api::catalogProducts');
$routes->get('api/user/product/(:num)', 'Rest_api::productDetails/$1');
$routes->get('api/user/related-products', 'Rest_api::relatedProducts');
$routes->get('api/user/product-reviews/(:num)', 'Rest_api::productReviews/$1');
$routes->post('api/user/product-reviews/(:num)', 'Rest_api::saveProductReview/$1');
$routes->post('api/user/coupon', 'Rest_api::validateCoupon');
$routes->get('api/user/orders', 'Rest_api::orders');
$routes->get('user/catalog', 'Dashboard::userCatalog');
$routes->get('user/cart', 'Dashboard::userCart');
$routes->get('user/product/(:num)', 'Dashboard::userProduct/$1');
$routes->get('user/orders', 'Dashboard::userOrders');
$routes->get('user/about', 'Pages::about');
$routes->get('user/contact', 'Pages::contact');
$routes->post('user/contact/submit', 'Pages::submitContact');
$routes->get('user/profile', 'Profile::show');
$routes->post('user/profile/update', 'Profile::update');
$routes->get('user/notifications', 'UserNotifications::index', ['filter' => 'auth']);
$routes->get('user/notifications/conversations', 'UserNotifications::conversations', ['filter' => 'auth']);
$routes->get('user/notifications/messages/(:num)', 'UserNotifications::messages/$1', ['filter' => 'auth']);
$routes->get('user/notifications/unread-count', 'UserNotifications::unreadCount', ['filter' => 'auth']);
$routes->post('user/notifications/create', 'UserNotifications::create', ['filter' => 'auth']);
$routes->post('user/notifications/send/(:num)', 'UserNotifications::send/$1', ['filter' => 'auth']);
$routes->post('user/notifications/read/(:num)', 'UserNotifications::markRead/$1', ['filter' => 'auth']);
$routes->get('admin/orders', 'Order::order_view');
$routes->post('admin/orders/update', 'Order::updateOrder');
$routes->get('admin/reports', 'Reports::reports_view');
$routes->post('admin/reports/data', 'Reports::reportData');
$routes->get('admin/payments', 'Payments::payments_view');
$routes->post('admin/payments/update', 'Payments::updatePayment');
$routes->post('admin/payments/sync-orders', 'Payments::syncFromOrders');
$routes->get('admin/billing', 'Billing::index');
$routes->post('admin/billing/save', 'Billing::save');
$routes->post('admin/billing/status', 'Billing::updateStatus');
$routes->post('admin/billing/delete', 'Billing::delete');
$routes->get('admin/delivery', 'Delivery::delivery_view');
$routes->post('admin/delivery/update', 'Delivery::updateDelivery');
$routes->post('admin/delivery/sync-orders', 'Delivery::syncFromOrders');
$routes->get('admin/returns', 'Returns::returns_view');
$routes->post('admin/returns/update', 'Returns::updateReturn');
$routes->get('admin/products', 'Products::product_view');
$routes->post('admin/products/add', 'Products::addProduct');
$routes->post('admin/products/update', 'Products::updateProduct');
$routes->post('admin/products/bulk-delete', 'Products::bulkDeleteProducts');
$routes->get('admin/categories', 'Categories::categories_view');
$routes->post('admin/categories/add', 'Categories::addCategory');
$routes->post('admin/categories/update', 'Categories::updateCategory');
$routes->get('admin/brands', 'Brands::brands_view');
$routes->post('admin/brands/add', 'Brands::addBrand');
$routes->post('admin/brands/update', 'Brands::updateBrand');
$routes->get('admin/customers', 'Customers::customers_view');
$routes->post('admin/customers/add', 'Customers::addCustomer');
$routes->post('admin/customers/update', 'Customers::updateCustomer');
$routes->get('admin/sellers', 'Sellers::sellers_view');
$routes->post('admin/sellers/add', 'Sellers::addSeller');
$routes->post('admin/sellers/update', 'Sellers::updateSeller');
$routes->get('admin/admins', 'Admins::admins_view');
$routes->post('admin/admins/add', 'Admins::addAdmin');
$routes->post('admin/admins/update', 'Admins::updateAdmin');
$routes->get('admin/banners', 'Banners::banners_view');
$routes->post('admin/banners/add', 'Banners::addBanner');
$routes->post('admin/banners/update', 'Banners::updateBanner');
$routes->get('admin/coupons', 'Coupons::coupons_view');
$routes->post('admin/coupons/add', 'Coupons::addCoupon');
$routes->post('admin/coupons/update', 'Coupons::updateCoupon');
$routes->get('admin/settings', 'Settings::settings_view');
$routes->post('admin/settings/general', 'Settings::saveGeneral');
$routes->post('admin/settings/payment', 'Settings::savePayment');
$routes->post('admin/settings/email', 'Settings::saveEmail');
$routes->post('admin/settings/system', 'Settings::saveSystem');
